/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FundamentalsRouteImport } from './routes/fundamentals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TestsAssignedRouteImport } from './routes/tests.assigned'
import { Route as TestsAssignRouteImport } from './routes/tests.assign'
import { Route as ProblemsIdRouteImport } from './routes/problems.$id'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as AdminProblemsRouteImport } from './routes/admin.problems'
import { Route as AdminFundamentalsRouteImport } from './routes/admin.fundamentals'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FundamentalsRoute = FundamentalsRouteImport.update({
  id: '/fundamentals',
  path: '/fundamentals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsAssignedRoute = TestsAssignedRouteImport.update({
  id: '/tests/assigned',
  path: '/tests/assigned',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsAssignRoute = TestsAssignRouteImport.update({
  id: '/tests/assign',
  path: '/tests/assign',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIdRoute = ProblemsIdRouteImport.update({
  id: '/problems/$id',
  path: '/problems/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProblemsRoute = AdminProblemsRouteImport.update({
  id: '/admin/problems',
  path: '/admin/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFundamentalsRoute = AdminFundamentalsRouteImport.update({
  id: '/admin/fundamentals',
  path: '/admin/fundamentals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fundamentals': typeof FundamentalsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fundamentals': typeof AdminFundamentalsRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/tests/assign': typeof TestsAssignRoute
  '/tests/assigned': typeof TestsAssignedRoute
  '/admin/': typeof AdminIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fundamentals': typeof FundamentalsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fundamentals': typeof AdminFundamentalsRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/tests/assign': typeof TestsAssignRoute
  '/tests/assigned': typeof TestsAssignedRoute
  '/admin': typeof AdminIndexRoute
  '/problems': typeof ProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fundamentals': typeof FundamentalsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fundamentals': typeof AdminFundamentalsRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/tests/assign': typeof TestsAssignRoute
  '/tests/assigned': typeof TestsAssignedRoute
  '/admin/': typeof AdminIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fundamentals'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/fundamentals'
    | '/admin/problems'
    | '/oauth/callback'
    | '/problems/$id'
    | '/tests/assign'
    | '/tests/assigned'
    | '/admin/'
    | '/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fundamentals'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/fundamentals'
    | '/admin/problems'
    | '/oauth/callback'
    | '/problems/$id'
    | '/tests/assign'
    | '/tests/assigned'
    | '/admin'
    | '/problems'
  id:
    | '__root__'
    | '/'
    | '/fundamentals'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/fundamentals'
    | '/admin/problems'
    | '/oauth/callback'
    | '/problems/$id'
    | '/tests/assign'
    | '/tests/assigned'
    | '/admin/'
    | '/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FundamentalsRoute: typeof FundamentalsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFundamentalsRoute: typeof AdminFundamentalsRoute
  AdminProblemsRoute: typeof AdminProblemsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  ProblemsIdRoute: typeof ProblemsIdRoute
  TestsAssignRoute: typeof TestsAssignRoute
  TestsAssignedRoute: typeof TestsAssignedRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundamentals': {
      id: '/fundamentals'
      path: '/fundamentals'
      fullPath: '/fundamentals'
      preLoaderRoute: typeof FundamentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/assigned': {
      id: '/tests/assigned'
      path: '/tests/assigned'
      fullPath: '/tests/assigned'
      preLoaderRoute: typeof TestsAssignedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/assign': {
      id: '/tests/assign'
      path: '/tests/assign'
      fullPath: '/tests/assign'
      preLoaderRoute: typeof TestsAssignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$id': {
      id: '/problems/$id'
      path: '/problems/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof ProblemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/problems': {
      id: '/admin/problems'
      path: '/admin/problems'
      fullPath: '/admin/problems'
      preLoaderRoute: typeof AdminProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fundamentals': {
      id: '/admin/fundamentals'
      path: '/admin/fundamentals'
      fullPath: '/admin/fundamentals'
      preLoaderRoute: typeof AdminFundamentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FundamentalsRoute: FundamentalsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFundamentalsRoute: AdminFundamentalsRoute,
  AdminProblemsRoute: AdminProblemsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  ProblemsIdRoute: ProblemsIdRoute,
  TestsAssignRoute: TestsAssignRoute,
  TestsAssignedRoute: TestsAssignedRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
